aws_profile: "default"
aws_region: "us-east-1" 
tf_state_bucket: "inventario-tfstate-rf2411" 
tf_state_key: "infra/terraform.tfstate"

project_name: "inventario"
domain_name: "" 
hosted_zone_id: "" 
waf_enable: true

frontend_bucket_name: "inventario-frontend-rf2411-prod" 
auth_frontend_bucket_name: "inventario-auth-rf2411-prod" 
uploads_bucket_name: "inventario-uploads-rf2411-prod" 

ecr_repo_prefix: "inventario-panel"
auth_context_dir: "../web_server/auth"
inventario_context_dir: "../web_server/inventario"
reportes_context_dir: "../web_server/reportes"
image_tag: "v1.0"

db_engine: "mysql"
db_engine_version: "8.0"
db_instance_class: "db.t4g.micro"
db_name: "inventario"
db_username: "admin_inventario" 
db_password: "1584Ro190" 

inventario_port: 3000
reportes_port: 3001
auth_port: 3002
desired_count_auth: 1
desired_count_inventario: 1
desired_count_reportes: 1

enable_nat_gateway: true
api_stage_name: "prod"

jwt_secret: "aB72/kLp3+O9sZJdG8rFmN4cK5jP6tQ8vW1xY2z" 

tags:
  Env: "Dev"
  Project: "Inventario"
